@startuml GoFishGame

skinparam ClassAttributeIconSize 0

abstract class Player {
    # hand: ArrayList<Card> // Re-sizable array of cards
    - books: int 
    - booksHeld: Text 

    + goFish(): void
    + drawCards(rank: int): void
    + hasRank(rank: int): boolean
    + updateHand(): void
}

note left of Player::booksHeld
    JavaFX text component indicating the no. of books held
end note

note left of Player::books
    No. of groups of four cards of the same rank
end note

class HumanPlayer {

}

note right of HumanPlayer
    Class that represents a Human player.
    Human players can pass input to the 
    game via their controls.

    The cards in the hand of a Human player
    are visible to the user.
end note

class CPUPlayer {

}

note right of CPUPlayer
    Class that represents a Computer player.
    Non-controllable and autonomous, randomly
    selects a rank of cards to request from
    the player. 
end note

class GoFish {
    - {static} currentPlayer: Player // Select randomly
    - {static} player: Player
    - {static} cpu: Player
    - {static} cardPool: Pool
}

class GameManager {

}

note right of GameManager
    Static Inner class of class GoFish
    that manages the state of the game:
    Players, turn, score, etcetera.    
end note

class Pool {
    - deck: ArrayList<Card>
    - img: ImageView
    - count: Text

    + draw(): Card
    + dealCards()
}

' note right of Pool
'     "Represents the deck of available cards"
' end note

class Card {
    - {static} validSuits: String[] = {"Clubs", "Diamonds", 
    "Hearts", "Spades"}
    - {static} rankMap: Map<Integer, String> = {1 -> "A", 11 -> "J", 
    12 -> "Q", 13 -> "K"}
    - rank: int
    - suit: String
}

class Card {
}

class PoolExhaustedException {

}

note right of PoolExhaustedException
    Subclass of `RuntimeException` that indicates
    that a player - or the pool - has run out of cards
end note

HumanPlayer --|> Player: extends
CPUPlayer --|> Player: extends
Player --> Pool: uses
Pool o--> Card: part of
GoFish *--> Pool: has a
PoolExhaustedException --> RuntimeException: extends
GameManager o--> GoFish: composite

@enduml